language: python
dist: bionic

env:
  global:
  - before_test='source $HOME/.local/nekrs/bin/nekrs.bashrc && cd $NEKRS_INSTALL_DIR'

cache:
  directories:
    - $HOME/.local/nekrs
    - $HOME/.occa

sudo: required

stages:
  - prepare
  - warmup
  - test

jobs:
  include:
   - stage: prepare
     name: "install"
     script: rm -rf $HOME/.occa $HOME/.local/nekrs && cd ${TRAVIS_BUILD_DIR} && OCCA_CUDA_ENABLED=0 ./makenrs 
   - stage: warmup
     name: "warm-up"
     script: $before_test && cd ethier && nrspre ethier 1  
   - stage: test
     name: "ethier default"
     script: $before_test && cd ethier && mpirun -np 2 nekrs --setup ethier --cimode 1 
   - stage: test
     name: "ethier oifs"
     script: $before_test && cd ethier && mpirun -np 2 nekrs --setup ethier --cimode 2 

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libmpich-dev mpich

install:

before_script:
